import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Headline from '../components/Headline'
import HomepageFooter from '../components/HomepageFooter'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Headline
          title="Welcome to Rick and Morty page!"
        />

        <nav>
          <ul>
            <li>
              <Link href="/characters">
                <a>Characters</a>
              </Link>
            </li>
            <li>
              <Link href="/locations">
                <a>Locations</a>
              </Link>
            </li>
            <li>
              <Link href="/episodes">
                <a>Episodes</a>
              </Link>
            </li>
          </ul>
        </nav>
      </main>

      <HomepageFooter
        date={2022}
        link="https://home.cesarczyk.dev"
        title='MCesarczyk'
      />
      
    </div>
  )
}

export default Home;